### PR TITLE
Get tasks from Exchange using EWS

### PR DESCRIPTION
**Pull request by ashuetawah**
Adding how to connect to EWS from same O365 API based MVC project.

### CODE REVIEW

**Comment by ashuetawah** [comment]
I have already singed CLA when submitting the PnP pulls this year. Please check and let me know.

**Comment by MIchaelMainer** [comment]
@ashuetawah, thank you for the pull request. We are reviewing your suggested changes and will respond soon.

**Comment by MIchaelMainer** [comment]
@ashuetawah, thank you very much for the contribution! Showing how to use EWS with the OAuth token is very useful. I like how you showed how to access tasks which haven't been exposed via the Office 365 APIs. With that said, we want to keep this sample's scope to just use the Office 365 APIs with the associated client libraries. I highly recommend that you keep your fork of this repo since this will be useful to refer to when someone is looking to use EWS and OAuth. You should go into your app registration on AAD and get a new client secret. You accidently published the client secret in your version of the web.config.
Again, thank you for the pull request. I'm sure many people will find it useful.

**Comment by iambmelt** [comment]
Based on the above, I'll close this PR for now.

Thanks again @ashuetawah for your contribution!

**Comment by ashuetawah** [comment]
Thanks for your time to look in to the contribution. I will update the client secret.

**Pull request closed without merging**
